[versions]
agp = "8.1.0"
firebase-firestore-ktx = "24.7.0"
google-hilt-android = "2.44"
lifecycle-runtime-compose = "2.6.2"
org-jetbrains-kotlin-android = "1.8.10"
core-ktx = "1.9.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
compose-bom = "2023.05.00"
material3 = "1.2.0-alpha11"
open-csv = "5.8"
constraint-layout = "1.0.1"
navigation = "2.5.0"
hilt = "1.1.0-alpha01"
hilt-android = "2.44"
play-services-code-scanner = "16.1.0"
qr-code = "3.5.1"
firebase-crashlytics-ktx = "18.4.3"
firebase-analytics-ktx = "21.3.0"
paging = "3.2.1"

[libraries]
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebase-firestore-ktx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "google-hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "google-hilt-android" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
play-services-code-scanner = { module = "com.google.android.gms:play-services-code-scanner", version.ref = "play-services-code-scanner" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material-icon-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
open-csv = { group = "com.opencsv", name = "opencsv", version.ref = "open-csv" }
constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraint-layout" }
navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
hilt = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt" }
qr-genartor = { group = "com.google.zxing", name = "core", version.ref = "qr-code" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebase-crashlytics-ktx" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebase-analytics-ktx" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }

[bundles]

